/**
 * End-to-end tests over real converted logs (fixtures generated by the
 * inspect_ai converter, `inspect log convert-chunked`, chunk_size=3 so
 * every sequence is multi-chunk). The load-bearing assertion is the twin
 * check: the TS skeleton producer over the reassembled event sequence must
 * reproduce the persisted `skeleton.json` byte-for-byte (as parsed JSON) on
 * every sample — pinning reader, chunk math, and producer against the
 * Python writer at once.
 */
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { messagesToStr } from "@tsmono/inspect-components/chat";

import { openZipFileFromBuffer } from "../../client/remote/remoteZipFile";
import { chunkedConversation } from "../conversation";
import { inMemoryMessageRows, type SampleMessagesData } from "../messageRows";
import { windowedMessageRows } from "../messageRowsWindowed";

import { openChunkedSample, type ChunkedSample } from "./chunkedSample";
import { decodeRange, type DecodeCtx } from "./decode";
import { classifySampleShape } from "./format";
import { RowSpace } from "./rowSpace";
import { sampleSkeleton } from "./skeleton";

const logsDir = join(
  process.cwd(),
  "src/log_data/chunked/fixtures/logs/chunked"
);

interface SampleRef {
  id: string;
  epoch: number;
}

interface OpenLog {
  entryNames: Set<string>;
  samples: SampleRef[];
  open: (ref: SampleRef) => Promise<ChunkedSample>;
}

const openLog = async (name: string): Promise<OpenLog> => {
  const bytes = new Uint8Array(readFileSync(join(logsDir, name)));
  const zip = await openZipFileFromBuffer(bytes);
  const entryNames = new Set(zip.centralDirectory.keys());
  const samples = [...entryNames]
    .map((entry) => /^samples\/(.+)_epoch_(\d+)\/sample\.json$/.exec(entry))
    .filter((m) => m !== null)
    .map((m) => ({ id: m[1] ?? "", epoch: Number(m[2]) }));
  return {
    entryNames,
    samples,
    open: (ref) => openChunkedSample(zip, entryNames, ref.id, ref.epoch),
  };
};

const logNames = readdirSync(logsDir).filter((name) => name.endsWith(".eval"));

const allVisible = () => true;

/** Walk a source's pages forward — pinning the cursor mechanics the
 *  production consumer (one whole-row-space read) doesn't exercise. */
const drainRows = async (source: SampleMessagesData, pageSize: number) => {
  const rows = [];
  let cursor: Record<string, unknown> | null = null;
  do {
    const page = await source.getRows({
      cursor,
      direction: "forward",
      limit: pageSize,
    });
    rows.push(...page.rows);
    cursor = page.nextCursor;
  } while (cursor !== null);
  return rows;
};

const decodeCtx = (
  sample: ChunkedSample,
  collapsed: ReadonlySet<string>,
  visible: (type: string) => boolean
): DecodeCtx => ({
  events: sample.events,
  stats: sample.stats,
  skel: sample.skel,
  isCollapsed: (spanId) => collapsed.has(spanId),
  visible,
});

describe("chunked corpus", () => {
  it("has fixture logs", () => {
    expect(logNames.length).toBeGreaterThanOrEqual(4);
  });

  it.each(logNames.map((name) => [name]))("%s", async (name) => {
    const log = await openLog(name);
    expect(log.samples.length).toBeGreaterThan(0);

    for (const ref of log.samples) {
      expect(classifySampleShape(log.entryNames, ref.id, ref.epoch)).toBe(
        "chunked"
      );
      const sample = await log.open(ref);

      // chunks recovered from entry names are contiguous and complete:
      // each chunk's name is the index of its first item
      for (const reader of [sample.messages, sample.calls]) {
        let itemCount = 0;
        for (let c = 0; c < reader.starts.length; c++) {
          expect(reader.starts[c]).toBe(itemCount);
          itemCount += (await reader.loadChunk(c)).length;
        }
      }

      // full reassembly matches the sample totals (the events count is
      // exact from the stats sidecar; message_refs bound the messages)
      const events = await sample.events.getRange(0, sample.events.knownCount);
      expect(events.length).toBe(sample.events.knownCount);
      expect(events.length).toBe(sample.skeleton.counts.events);
      const messages = await sample.messages.getRange(
        0,
        Number.MAX_SAFE_INTEGER
      );
      const lastStart = sample.messages.starts.at(-1);
      if (lastStart !== undefined) {
        expect(messages.length).toBeGreaterThan(lastStart);
      }

      // events/uuids.json resolves event uuids to ordinals (old logs may
      // have events without uuids — those simply have no map entry)
      const withUuid = events.flatMap((e, ordinal) =>
        e.uuid ? [{ uuid: e.uuid, ordinal }] : []
      );
      for (const { uuid, ordinal } of withUuid.filter(
        (_, i) => i === 0 || i === withUuid.length - 1
      )) {
        expect(await sample.uuidToOrdinal(uuid)).toBe(ordinal);
      }
      expect(await sample.uuidToOrdinal("no-such-uuid")).toBeUndefined();

      // the stats sidecar is a pure function of the chunking
      expect(sample.stats.length).toBe(sample.events.starts.length);
      sample.stats.forEach((chunkStats, c) => {
        const [lo, hi] = sample.events.chunkBounds(c);
        expect(chunkStats.start).toBe(lo);
        const chunk = events.slice(lo, hi);
        const counts: Record<string, number> = {};
        for (const ev of chunk) {
          counts[ev.event] = (counts[ev.event] ?? 0) + 1;
        }
        expect(chunkStats.type_counts).toStrictEqual(counts);
        const first = chunk[0];
        const last = chunk[chunk.length - 1];
        expect(chunkStats.first.type).toBe(first?.event);
        expect(chunkStats.last.type).toBe(last?.event);
        expect(chunkStats.first.span_id ?? null).toBe(first?.span_id ?? null);
        expect(chunkStats.last.span_id ?? null).toBe(last?.span_id ?? null);
      });

      // the twin check: TS producer over reassembled events == persisted skeleton
      expect(sampleSkeleton(events)).toStrictEqual(sample.skeleton);

      // the final conversation reads from message_refs, fully resolved
      const conv = chunkedConversation(sample);
      const conversation = await conv.getMessages(0, conv.messageCount);
      const refWidths = sample.shell.message_refs.reduce(
        (n, [start, end]) => n + (end - start),
        0
      );
      expect(conversation.length).toBe(refWidths);
      expect(JSON.stringify(conversation)).not.toContain('"attachment://');

      // windows through the conversation seam equal slices of the full
      // read (positional reads never depend on what else was read)
      expect(conv.messageCount).toBe(refWidths);
      const n = conv.messageCount;
      const windows: [number, number][] = [
        [0, Math.min(3, n)],
        [Math.floor(n / 2), Math.min(Math.floor(n / 2) + 3, n)],
        [Math.max(0, n - 3), n],
        [n, n + 5],
      ];
      for (const [lo, hi] of windows) {
        expect(await conv.getMessages(lo, hi)).toStrictEqual(
          conversation.slice(lo, hi)
        );
      }

      // the windowed rows source over real multi-chunk logs (chunk_size=3
      // — every page crosses chunks) equals the in-memory fold of the
      // whole conversation, at any page size
      const rowsOracle = await inMemoryMessageRows(conversation).getRows({
        cursor: null,
        direction: "forward",
        limit: Number.MAX_SAFE_INTEGER,
      });
      for (const pageSize of [1, 7, 1000]) {
        const source = windowedMessageRows(chunkedConversation(sample));
        expect(await drainRows(source, pageSize)).toEqual(rowsOracle.rows);
      }

      // exportText streams the exact whole-conversation text
      const exportSource = windowedMessageRows(chunkedConversation(sample));
      const parts: string[] = [];
      for await (const part of exportSource.exportText()) {
        parts.push(part);
      }
      expect(parts.join("")).toBe(messagesToStr(conversation));

      // decode walk, everything visible and expanded
      const expanded = new RowSpace(
        sample.events,
        sample.stats,
        sample.skel,
        new Set(),
        allVisible
      );
      const ctx = decodeCtx(sample, new Set(), allVisible);
      await Promise.all(
        sample.stats.map((_, c) => expanded.materialize(c, ctx))
      );
      expect(expanded.exact.every(Boolean)).toBe(true);

      const rows = Array.from({ length: expanded.total }, (_, i) => {
        const slot = expanded.slotAt(i);
        expect(slot.kind).toBe("row");
        return slot.kind === "row" ? slot.row : undefined;
      }).filter((row) => row !== undefined);
      expect(rows.length).toBe(expanded.total);

      // ordinals strictly increase; every span with visible contents gets one row
      rows.forEach((row, i) => {
        const prev = rows[i - 1];
        if (prev) {
          expect(row.ordinal).toBeGreaterThan(prev.ordinal);
        }
      });
      const spanRowIdxs = rows
        .filter((row) => row.kind === "span")
        .map((row) => row.spanIdx)
        .sort((a, b) => a - b);
      const visibleSpans = sample.skeleton.spans
        .map((_, i) => i)
        .filter((i) => sample.skel.hasVisibleContents(i, allVisible));
      expect(spanRowIdxs).toStrictEqual(visibleSpans);

      // the ordinal anchor is exact once materialized
      rows.forEach((row, i) => {
        expect(expanded.rowIndexForOrdinal(row.ordinal)).toBe(i);
      });

      // collapse-all: interiors elide — no row lands strictly inside a span
      const allSpanIds = new Set(sample.skeleton.spans.map((span) => span.id));
      const collapsedSpace = new RowSpace(
        sample.events,
        sample.stats,
        sample.skel,
        allSpanIds,
        allVisible
      );
      const collapsedCtx = decodeCtx(sample, allSpanIds, allVisible);
      await Promise.all(
        sample.stats.map((_, c) => collapsedSpace.materialize(c, collapsedCtx))
      );
      expect(collapsedSpace.total).toBeLessThanOrEqual(expanded.total);
      for (let i = 0; i < collapsedSpace.total; i++) {
        const slot = collapsedSpace.slotAt(i);
        expect(slot.kind).toBe("row");
        if (slot.kind === "row") {
          const inside = sample.skeleton.spans.some(
            (span) =>
              slot.row.ordinal > span.begin &&
              slot.row.ordinal <= span.extent[1]
          );
          expect(inside).toBe(false);
        }
      }

      // filter pushdown: an impossible filter decodes to structure-only rows
      // without erroring, and never emits event rows
      const filtered = await decodeRange(
        decodeCtx(sample, new Set(), (type) => type === "no_such_type"),
        0,
        sample.events.knownCount,
        false
      );
      expect(filtered.every((row) => row.kind !== "event")).toBe(true);
    }
  });
});
