// Captured from picomatch 4.0.7 with nobrace, nonegate, and noextglob enabled.
// Keep these expectations independent of the replacement matcher.
export const scannerGlobCompatibility = {
  names: [
    "a",
    "b",
    "ab",
    "a.a",
    "a-b",
    ".a",
    "aa",
    "abc",
    "c",
    "!",
    "pkg",
    "pkg/a",
    "pkg/b",
    "pkg/.a",
    "pkg/sub/a",
    "pkg/.sub/a",
    ".pkg/a",
    "a/b",
    "a/a",
    "b/a",
    "ab/a",
    "a/.a",
    "a/x/b",
    "a/x/y/b",
    "pkg/a/b",
    "a/",
    "pkg/a/",
    "pkg/a/b/",
    "pkg/",
  ],
  cases: [
    {
      pattern: "a",
      matchingNames: ["a"],
    },
    {
      pattern: "pkg/a",
      matchingNames: ["pkg/a"],
    },
    {
      pattern: "a/a",
      matchingNames: ["a/a"],
    },
    {
      pattern: "**/a",
      matchingNames: ["a", "pkg/a", "pkg/sub/a", "a/a", "b/a", "ab/a"],
    },
    {
      pattern: "pkg/**/a",
      matchingNames: ["pkg/a", "pkg/sub/a"],
    },
    {
      pattern: "a/**",
      matchingNames: ["a", "a/b", "a/a", "a/x/b", "a/x/y/b", "a/"],
    },
    {
      pattern: "a/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b"],
    },
    {
      pattern: "**/a/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b", "pkg/a/b"],
    },
    {
      pattern: "b",
      matchingNames: ["b"],
    },
    {
      pattern: "pkg/b",
      matchingNames: ["pkg/b"],
    },
    {
      pattern: "b/a",
      matchingNames: ["b/a"],
    },
    {
      pattern: "**/b",
      matchingNames: ["b", "pkg/b", "a/b", "a/x/b", "a/x/y/b", "pkg/a/b"],
    },
    {
      pattern: "pkg/**/b",
      matchingNames: ["pkg/b", "pkg/a/b"],
    },
    {
      pattern: "b/**",
      matchingNames: ["b", "b/a"],
    },
    {
      pattern: "b/**/b",
      matchingNames: [],
    },
    {
      pattern: "**/b/**/b",
      matchingNames: [],
    },
    {
      pattern: "ab",
      matchingNames: ["ab"],
    },
    {
      pattern: "pkg/ab",
      matchingNames: [],
    },
    {
      pattern: "ab/a",
      matchingNames: ["ab/a"],
    },
    {
      pattern: "**/ab",
      matchingNames: ["ab"],
    },
    {
      pattern: "pkg/**/ab",
      matchingNames: [],
    },
    {
      pattern: "ab/**",
      matchingNames: ["ab", "ab/a"],
    },
    {
      pattern: "ab/**/b",
      matchingNames: [],
    },
    {
      pattern: "**/ab/**/b",
      matchingNames: [],
    },
    {
      pattern: ".a",
      matchingNames: [".a"],
    },
    {
      pattern: "pkg/.a",
      matchingNames: ["pkg/.a"],
    },
    {
      pattern: ".a/a",
      matchingNames: [],
    },
    {
      pattern: "**/.a",
      matchingNames: [".a", "pkg/.a", "a/.a"],
    },
    {
      pattern: "pkg/**/.a",
      matchingNames: ["pkg/.a"],
    },
    {
      pattern: ".a/**",
      matchingNames: [".a"],
    },
    {
      pattern: ".a/**/b",
      matchingNames: [],
    },
    {
      pattern: "**/.a/**/b",
      matchingNames: [],
    },
    {
      pattern: "*",
      matchingNames: [
        "a",
        "b",
        "ab",
        "a.a",
        "a-b",
        "aa",
        "abc",
        "c",
        "!",
        "pkg",
        "a/",
        "pkg/",
      ],
    },
    {
      pattern: "pkg/*",
      matchingNames: ["pkg/a", "pkg/b", "pkg/a/"],
    },
    {
      pattern: "*/a",
      matchingNames: ["pkg/a", "a/a", "b/a", "ab/a"],
    },
    {
      pattern: "**/*",
      matchingNames: [
        "a",
        "b",
        "ab",
        "a.a",
        "a-b",
        "aa",
        "abc",
        "c",
        "!",
        "pkg",
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "a/b",
        "a/a",
        "b/a",
        "ab/a",
        "a/x/b",
        "a/x/y/b",
        "pkg/a/b",
        "a/",
        "pkg/a/",
        "pkg/a/b/",
        "pkg/",
      ],
    },
    {
      pattern: "pkg/**/*",
      matchingNames: [
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "pkg/a/b",
        "pkg/a/",
        "pkg/a/b/",
      ],
    },
    {
      pattern: "*/**",
      matchingNames: [
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "a/b",
        "a/a",
        "b/a",
        "ab/a",
        "a/x/b",
        "a/x/y/b",
        "pkg/a/b",
        "a/",
        "pkg/a/",
        "pkg/a/b/",
        "pkg/",
      ],
    },
    {
      pattern: "*/**/b",
      matchingNames: ["pkg/b", "a/b", "a/x/b", "a/x/y/b", "pkg/a/b"],
    },
    {
      pattern: "**/*/**/b",
      matchingNames: ["pkg/b", "a/b", "a/x/b", "a/x/y/b", "pkg/a/b"],
    },
    {
      pattern: "?",
      matchingNames: ["a", "b", "c", "!"],
    },
    {
      pattern: "pkg/?",
      matchingNames: ["pkg/a", "pkg/b"],
    },
    {
      pattern: "?/a",
      matchingNames: ["a/a", "b/a"],
    },
    {
      pattern: "**/?",
      matchingNames: [
        "a",
        "b",
        "c",
        "!",
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "a/b",
        "a/a",
        "b/a",
        "ab/a",
        "a/x/b",
        "a/x/y/b",
        "pkg/a/b",
      ],
    },
    {
      pattern: "pkg/**/?",
      matchingNames: ["pkg/a", "pkg/b", "pkg/sub/a", "pkg/a/b"],
    },
    {
      pattern: "?/**",
      matchingNames: [
        "a",
        "b",
        "c",
        "!",
        "a/b",
        "a/a",
        "b/a",
        "a/x/b",
        "a/x/y/b",
        "a/",
      ],
    },
    {
      pattern: "?/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b"],
    },
    {
      pattern: "**/?/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b", "pkg/a/b"],
    },
    {
      pattern: "a*",
      matchingNames: ["a", "ab", "a.a", "a-b", "aa", "abc"],
    },
    {
      pattern: "pkg/a*",
      matchingNames: ["pkg/a", "pkg/a/"],
    },
    {
      pattern: "a*/a",
      matchingNames: ["a/a", "ab/a"],
    },
    {
      pattern: "**/a*",
      matchingNames: [
        "a",
        "ab",
        "a.a",
        "a-b",
        "aa",
        "abc",
        "pkg/a",
        "pkg/sub/a",
        "a/a",
        "b/a",
        "ab/a",
        "a/",
        "pkg/a/",
      ],
    },
    {
      pattern: "pkg/**/a*",
      matchingNames: ["pkg/a", "pkg/sub/a", "pkg/a/"],
    },
    {
      pattern: "a*/**",
      matchingNames: ["a/b", "a/a", "ab/a", "a/x/b", "a/x/y/b", "a/"],
    },
    {
      pattern: "a*/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b"],
    },
    {
      pattern: "**/a*/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b", "pkg/a/b"],
    },
    {
      pattern: "*a",
      matchingNames: ["a", "a.a", "aa"],
    },
    {
      pattern: "pkg/*a",
      matchingNames: ["pkg/a"],
    },
    {
      pattern: "*a/a",
      matchingNames: ["a/a"],
    },
    {
      pattern: "**/*a",
      matchingNames: [
        "a",
        "a.a",
        "aa",
        "pkg/a",
        "pkg/sub/a",
        "a/a",
        "b/a",
        "ab/a",
      ],
    },
    {
      pattern: "pkg/**/*a",
      matchingNames: ["pkg/a", "pkg/sub/a"],
    },
    {
      pattern: "*a/**",
      matchingNames: ["a", "a.a", "aa", "a/b", "a/a", "a/x/b", "a/x/y/b", "a/"],
    },
    {
      pattern: "*a/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b"],
    },
    {
      pattern: "**/*a/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b", "pkg/a/b"],
    },
    {
      pattern: "a?",
      matchingNames: ["ab", "aa"],
    },
    {
      pattern: "pkg/a?",
      matchingNames: [],
    },
    {
      pattern: "a?/a",
      matchingNames: ["ab/a"],
    },
    {
      pattern: "**/a?",
      matchingNames: ["ab", "aa"],
    },
    {
      pattern: "pkg/**/a?",
      matchingNames: [],
    },
    {
      pattern: "a?/**",
      matchingNames: ["ab", "aa", "ab/a"],
    },
    {
      pattern: "a?/**/b",
      matchingNames: [],
    },
    {
      pattern: "**/a?/**/b",
      matchingNames: [],
    },
    {
      pattern: "?a",
      matchingNames: ["aa"],
    },
    {
      pattern: "pkg/?a",
      matchingNames: [],
    },
    {
      pattern: "?a/a",
      matchingNames: [],
    },
    {
      pattern: "**/?a",
      matchingNames: ["aa"],
    },
    {
      pattern: "pkg/**/?a",
      matchingNames: [],
    },
    {
      pattern: "?a/**",
      matchingNames: ["aa"],
    },
    {
      pattern: "?a/**/b",
      matchingNames: [],
    },
    {
      pattern: "**/?a/**/b",
      matchingNames: [],
    },
    {
      pattern: ".*",
      matchingNames: [".a"],
    },
    {
      pattern: "pkg/.*",
      matchingNames: ["pkg/.a"],
    },
    {
      pattern: ".*/a",
      matchingNames: [".pkg/a"],
    },
    {
      pattern: "**/.*",
      matchingNames: [".a", "pkg/.a", "a/.a"],
    },
    {
      pattern: "pkg/**/.*",
      matchingNames: ["pkg/.a"],
    },
    {
      pattern: ".*/**",
      matchingNames: [".pkg/a"],
    },
    {
      pattern: ".*/**/b",
      matchingNames: [],
    },
    {
      pattern: "**/.*/**/b",
      matchingNames: [],
    },
    {
      pattern: "[ab]",
      matchingNames: ["a", "b", "a/"],
    },
    {
      pattern: "pkg/[ab]",
      matchingNames: ["pkg/a", "pkg/b", "pkg/a/"],
    },
    {
      pattern: "[ab]/a",
      matchingNames: ["a/a", "b/a"],
    },
    {
      pattern: "**/[ab]",
      matchingNames: [
        "a",
        "b",
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "a/b",
        "a/a",
        "b/a",
        "ab/a",
        "a/x/b",
        "a/x/y/b",
        "pkg/a/b",
        "a/",
        "pkg/a/",
        "pkg/a/b/",
      ],
    },
    {
      pattern: "pkg/**/[ab]",
      matchingNames: [
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "pkg/a/b",
        "pkg/a/",
        "pkg/a/b/",
      ],
    },
    {
      pattern: "[ab]/**",
      matchingNames: ["a", "b", "a/b", "a/a", "b/a", "a/x/b", "a/x/y/b", "a/"],
    },
    {
      pattern: "[ab]/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b"],
    },
    {
      pattern: "**/[ab]/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b", "pkg/a/b"],
    },
    {
      pattern: "[a-c]",
      matchingNames: ["a", "b", "c", "a/"],
    },
    {
      pattern: "pkg/[a-c]",
      matchingNames: ["pkg/a", "pkg/b", "pkg/a/"],
    },
    {
      pattern: "[a-c]/a",
      matchingNames: ["a/a", "b/a"],
    },
    {
      pattern: "**/[a-c]",
      matchingNames: [
        "a",
        "b",
        "c",
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "a/b",
        "a/a",
        "b/a",
        "ab/a",
        "a/x/b",
        "a/x/y/b",
        "pkg/a/b",
        "a/",
        "pkg/a/",
        "pkg/a/b/",
      ],
    },
    {
      pattern: "pkg/**/[a-c]",
      matchingNames: [
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "pkg/a/b",
        "pkg/a/",
        "pkg/a/b/",
      ],
    },
    {
      pattern: "[a-c]/**",
      matchingNames: [
        "a",
        "b",
        "c",
        "a/b",
        "a/a",
        "b/a",
        "a/x/b",
        "a/x/y/b",
        "a/",
      ],
    },
    {
      pattern: "[a-c]/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b"],
    },
    {
      pattern: "**/[a-c]/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b", "pkg/a/b"],
    },
    {
      pattern: "[^a]",
      matchingNames: ["b", "c", "!"],
    },
    {
      pattern: "pkg/[^a]",
      matchingNames: ["pkg/b"],
    },
    {
      pattern: "[^a]/a",
      matchingNames: ["b/a"],
    },
    {
      pattern: "**/[^a]",
      matchingNames: [
        "b",
        "c",
        "!",
        "pkg/b",
        "a/b",
        "a/x/b",
        "a/x/y/b",
        "pkg/a/b",
        "pkg/a/b/",
      ],
    },
    {
      pattern: "pkg/**/[^a]",
      matchingNames: ["pkg/b", "pkg/a/b", "pkg/a/b/"],
    },
    {
      pattern: "[^a]/**",
      matchingNames: ["b", "c", "!", "b/a"],
    },
    {
      pattern: "[^a]/**/b",
      matchingNames: [],
    },
    {
      pattern: "**/[^a]/**/b",
      matchingNames: ["a/x/b", "a/x/y/b"],
    },
    {
      pattern: "[!a]",
      matchingNames: ["a", "!", "a/"],
    },
    {
      pattern: "pkg/[!a]",
      matchingNames: ["pkg/a", "pkg/a/"],
    },
    {
      pattern: "[!a]/a",
      matchingNames: ["a/a"],
    },
    {
      pattern: "**/[!a]",
      matchingNames: [
        "a",
        "!",
        "pkg/a",
        "pkg/sub/a",
        "a/a",
        "b/a",
        "ab/a",
        "a/",
        "pkg/a/",
      ],
    },
    {
      pattern: "pkg/**/[!a]",
      matchingNames: ["pkg/a", "pkg/sub/a", "pkg/a/"],
    },
    {
      pattern: "[!a]/**",
      matchingNames: ["a", "!", "a/b", "a/a", "a/x/b", "a/x/y/b", "a/"],
    },
    {
      pattern: "[!a]/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b"],
    },
    {
      pattern: "**/[!a]/**/b",
      matchingNames: ["a/b", "a/x/b", "a/x/y/b", "pkg/a/b"],
    },
    {
      pattern: "**",
      matchingNames: [
        "a",
        "b",
        "ab",
        "a.a",
        "a-b",
        "aa",
        "abc",
        "c",
        "!",
        "pkg",
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "a/b",
        "a/a",
        "b/a",
        "ab/a",
        "a/x/b",
        "a/x/y/b",
        "pkg/a/b",
        "a/",
        "pkg/a/",
        "pkg/a/b/",
        "pkg/",
      ],
    },
    {
      pattern: "pkg/**",
      matchingNames: [
        "pkg",
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "pkg/a/b",
        "pkg/a/",
        "pkg/a/b/",
        "pkg/",
      ],
    },
    {
      pattern: "**/a",
      matchingNames: ["a", "pkg/a", "pkg/sub/a", "a/a", "b/a", "ab/a"],
    },
    {
      pattern: "**/**",
      matchingNames: [
        "a",
        "b",
        "ab",
        "a.a",
        "a-b",
        "aa",
        "abc",
        "c",
        "!",
        "pkg",
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "a/b",
        "a/a",
        "b/a",
        "ab/a",
        "a/x/b",
        "a/x/y/b",
        "pkg/a/b",
        "a/",
        "pkg/a/",
        "pkg/a/b/",
        "pkg/",
      ],
    },
    {
      pattern: "pkg/**/**",
      matchingNames: [
        "pkg",
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "pkg/a/b",
        "pkg/a/",
        "pkg/a/b/",
        "pkg/",
      ],
    },
    {
      pattern: "**/**",
      matchingNames: [
        "a",
        "b",
        "ab",
        "a.a",
        "a-b",
        "aa",
        "abc",
        "c",
        "!",
        "pkg",
        "pkg/a",
        "pkg/b",
        "pkg/sub/a",
        "a/b",
        "a/a",
        "b/a",
        "ab/a",
        "a/x/b",
        "a/x/y/b",
        "pkg/a/b",
        "a/",
        "pkg/a/",
        "pkg/a/b/",
        "pkg/",
      ],
    },
    {
      pattern: "**/**/b",
      matchingNames: ["b", "pkg/b", "a/b", "a/x/b", "a/x/y/b", "pkg/a/b"],
    },
    {
      pattern: "**/**/**/b",
      matchingNames: ["b", "pkg/b", "a/b", "a/x/b", "a/x/y/b", "pkg/a/b"],
    },
  ],
};
