import {
  CellStyleModule,
  ClientSideRowModelModule,
  ColumnApiModule,
  ColumnAutoSizeModule,
  DateFilterModule,
  EventApiModule,
  GridStateModule,
  ModuleRegistry,
  NumberFilterModule,
  RowApiModule,
  RowAutoHeightModule,
  RowSelectionModule,
  RowStyleModule,
  ScrollApiModule,
  TextFilterModule,
  TooltipModule,
  ValidationModule,
} from "ag-grid-community";

// Replaces AllCommunityModule with only the modules scout actually uses,
// which trims ~hundreds of KB from the ag-grid contribution to the bundle.
ModuleRegistry.registerModules([
  ClientSideRowModelModule,
  ColumnApiModule,
  ColumnAutoSizeModule,
  GridStateModule,
  RowApiModule,
  RowAutoHeightModule,
  RowSelectionModule,
  ScrollApiModule,
  CellStyleModule,
  RowStyleModule,
  EventApiModule,
  TextFilterModule,
  NumberFilterModule,
  DateFilterModule,
  TooltipModule,
  ValidationModule,
]);
