/**
 * Generate TypeScript types from the JSON Schema.
 *
 * Reads log-schema.json and generates src/@types/log.d.ts using
 * json-schema-to-typescript.
 */
import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { fileURLToPath } from "url";

import { compile } from "json-schema-to-typescript";

import { requirePythonRepoRoot } from "../../../tooling/python-repo/index.js";

const __dirname = resolve(fileURLToPath(import.meta.url), "..");
const appRoot = resolve(__dirname, "..");

const pythonRoot = requirePythonRepoRoot("inspect_ai");
const schemaPath = resolve(pythonRoot, "src/inspect_ai/_view/log-schema.json");
const typesPath = resolve(appRoot, "src/@types/log.d.ts");

const BANNER = `/*
 *  This file is automatically generated by schema.py
 *  DO NOT MODIFY IT BY HAND.
 *  To regenerate, run: python src/inspect_ai/_view/schema.py
 */`;

const schema = JSON.parse(readFileSync(schemaPath, "utf-8"));
let output = await compile(schema, "EvalLog", {
  additionalProperties: false,
  bannerComment: BANNER,
});

// Replace the generated `JsonValue = unknown` alias with an import of the
// shared JsonValue type from @tsmono/util, and fix `internal: unknown` fields.
output = output.replace(/internal: unknown;/g, "internal: JsonValue;");
output = output.replace(/export type JsonValue = unknown;\n?/, "");
const JSON_VALUE_IMPORT = 'import { JsonValue } from "@tsmono/util";\n';
output = BANNER + "\n" + JSON_VALUE_IMPORT + output.replace(BANNER, "");

writeFileSync(typesPath, output);
