/**
 * Generate TypeScript types from the JSON Schema.
 *
 * Reads log-schema.json and generates src/@types/log.d.ts using
 * json-schema-to-typescript.
 */
import { execSync } from "child_process";
import { resolve } from "path";
import { fileURLToPath } from "url";

const __dirname = resolve(fileURLToPath(import.meta.url), "..");
const appRoot = resolve(__dirname, "..");

const schemaPath = resolve(appRoot, "log-schema.json");
const typesPath = resolve(appRoot, "src/@types/log.d.ts");

const BANNER = `/*
 *  This file is automatically generated by schema.py
 *  DO NOT MODIFY IT BY HAND.
 *  To regenerate, run: python src/inspect_ai/_view/schema.py
 */`;

execSync(
  [
    "npx",
    "json2ts",
    "--input",
    schemaPath,
    "--output",
    typesPath,
    "--additionalProperties",
    "false",
    "--bannerComment",
    JSON.stringify(BANNER),
  ].join(" "),
  { cwd: appRoot, stdio: "inherit" },
);

execSync(`npx prettier --write ${typesPath}`, {
  cwd: appRoot,
  stdio: "inherit",
});
